apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask

metadata:
  name: update-prod
  namespace: gitops-demo

spec:
  steps:

    - uses: git-clone
      config:
        repoURL: https://github.com/manibratam1221/gitops-demo.git
        checkout:
          - branch: main
            path: ./repo

    - uses: yaml-parse
      as: stageImage

      config:
        path: ./repo/stage/deployment.yaml

        outputs:
          - name: image
            fromExpression: spec.template.spec.containers[0].image

    - uses: yaml-update

      config:
        path: ./repo/prod/deployment.yaml

        updates:
          - key: spec.template.spec.containers.0.image
            value: ${{ task.outputs.stageImage.image }}

    - uses: git-commit
      as: commit

      config:
        path: ./repo
        message: Promote stage image to production

    - uses: git-push

      config:
        path: ./repo

    - uses: argocd-update

      config:
        apps:
          - name: prod-app
