apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gitops-demo
  namespace: gitops-demo
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/manibratam1221/gitops-demo.git
        branch: main
        commitSelectionStrategy: NewestFromBranch
