name: Promote to Production

on:
  push:
    branches:
      - main
    paths:
      - "stage/**"

jobs:
  promote:
    runs-on: self-hosted

    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure kubectl
        run: |
          kubectl version --client
          kubectl get nodes

      - name: Get Commit SHA
        run: |
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

          - name: Wait for matching Freight
            shell: bash
            run: |
              echo "Waiting for Freight for commit ${COMMIT_SHA}"
              for i in {1..30}; do
              FREIGHT=$(kubectl get freight -n kargo -o json \
              | jq -r --arg SHA "$COMMIT_SHA" '
                .items[]
                | select(
                    .status.commits[]?.id == $SHA
                  )
              | .metadata.name' | head -1)

            if [[ -n "$FREIGHT" ]]; then
               echo "FREIGHT_NAME=$FREIGHT" >> $GITHUB_ENV
              exit 0
            fi

            sleep 10

          done

          exit 1

      - name: Promote
        run: |
          kargo promote \
            -p gitops-demo \
            --stage stage \
            --freight "${FREIGHT_NAME}" \
            --insecure-skip-tls-verify

      - name: Create Promotion
        shell: bash
        run: |

          cat <<EOF | kubectl apply -f -

          apiVersion: kargo.akuity.io/v1alpha1
          kind: Promotion

          metadata:
            generateName: github-promotion-

          spec:
            stage: stage
            freight: ${FREIGHT_NAME}

          EOF

      - name: Watch Promotion
        run: |

          kubectl get promotions -A

          kubectl wait \
            --for=jsonpath='{.status.phase}'=Succeeded \
            promotion \
            --all \
            -n kargo \
            --timeout=5m
