name: Promote to Production

on:
  push:
    branches:
      - main
    paths:
      - "stage/**"

jobs:
  promote:

    runs-on: self-hosted

    environment:
      name: production

    env:
      PROJECT: gitops-demo
      STAGE: stage

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Cluster Connectivity
        run: |
          kubectl version --client
          kubectl get nodes
          kubectl get stages -n gitops-demo
          kubectl get freight -n gitops-demo

      - name: Install Kargo CLI
        run: |
          if ! command -v kargo >/dev/null 2>&1; then
            curl -L \
              https://github.com/akuity/kargo/releases/latest/download/kargo-linux-amd64 \
              -o kargo

            chmod +x kargo
            sudo mv kargo /usr/local/bin/
          fi

          kargo version

      - name: Login to Kargo
        run: |
          kargo login \
            "${{ secrets.KARGO_SERVER }}" \
            --token "${{ secrets.KARGO_TOKEN }}" \
            --insecure-skip-tls-verify

      - name: Save Commit SHA
        run: |
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Wait for Matching Freight
        shell: bash
        run: |

          echo "Waiting for Freight for commit ${COMMIT_SHA}"

          ATTEMPTS=30

          until [ $ATTEMPTS -eq 0 ]
          do

            FREIGHT=$(kubectl get freight -n kargo -o json \
            | jq -r --arg SHA "$COMMIT_SHA" '
                .items[]
                | select(
                    any(.status.commits[]?; .id==$SHA)
                  )
                | .metadata.name
              ' | head -n1)

            if [[ -n "$FREIGHT" ]]; then

              echo "Matching Freight Found : $FREIGHT"

              echo "FREIGHT_NAME=$FREIGHT" >> $GITHUB_ENV

              exit 0

            fi

            echo "No Freight yet..."

            ATTEMPTS=$((ATTEMPTS-1))

            sleep 10

          done

          echo "Timed out waiting for Freight."

          exit 1

      - name: Display Freight
        run: |
          echo "Freight = ${FREIGHT_NAME}"

      - name: Promote Freight
        run: |

          kargo promote \
            -p "${PROJECT}" \
            --stage "${STAGE}" \
            --freight "${FREIGHT_NAME}" \
            --insecure-skip-tls-verify

      - name: Wait for Promotion
        run: |

          echo "Waiting for Promotion..."

          sleep 5

          kubectl get promotions -n gitops-demo

          kubectl wait \
            --for=jsonpath='{.status.phase}'=Succeeded \
            promotion \
            --all \
            -n gitops-demo \
            --timeout=300s

      - name: Verify ArgoCD
        run: |

          kubectl get applications -n argocd

          kubectl wait \
            application/prod-app \
            -n argocd \
            --for=jsonpath='{.status.health.status}'=Healthy \
            --timeout=300s

      - name: Success
        run: |
          echo "Production Promotion Successful 🚀"
